### PR TITLE
Add xml support

### PR DESCRIPTION
**Pull request by HRogge**
Add basic from_xml/to_xml support to yangson.
anydata/anyxml is not supported at the moment because of trouble with the RFC definitions of XML encoding. IETF netconf group suggests dropping anyxml and only allowing anydata with existing YANG schema.

### CODE REVIEW

**Comment by llhotka** [comment]
Great, thanks! I will test it with some examples.

**Comment by HRogge** [comment]
I have added some more fixes to the branch... and added a custom XML parser in yangson/xmlparser.py. The original python etree.ElementTree parser does not give us access to the xmlns attributes, which are needed for the IdentityRef parser.

**Comment by HRogge** [comment]
Just to explain the last commits, the filter system allows to implement things like the depth/fields operator within the xml/json serializer of the library.

**Comment by llhotka** [comment]
I tried it with this data: [tacacsplus.tar.gz](https://github.com/CZ-NIC/yangson/files/4608792/tacacsplus.tar.gz)
```
(yangson) $ python test.py 
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    inst = dm.from_xml(etr.getroot())
  ...
  File "/home/lhotka/Projects/yangson/yangson/schemanode.py", line 493, in _process_xmlobj_child
    raise RawMemberError(npath)
yangson.exceptions.RawMemberError: /ietf-system:system/ietf-system:dns-resolver/ietf-system:server/0/ietf-system:timeout
```
It seems that the `server` node under `ietf-system:dns-resolver` is somehow confused with `ietf-system-tacacsplus:server` (which has the `timeout` child).

**Comment by HRogge** [comment]
Did you use the XmlParser class in yangson.xmlparser? If not please try, because it is necessary to get the namespace information. The default etree-parser throws all namespace information not necessary for the local tag name away.

**Comment by HRogge** [comment]
I think I managed to reproduce the bug... I am working on a solution.

**Comment by HRogge** [comment]
I think I fixed the problem, I was able to load your "example-data.xml" into my server code.
I really want a testcase that contains ALL possible datatypes for Restconf, both for JSON and XML.

**Comment by llhotka** [comment]
`make test` fails on your `xml` branch.

**Comment by HRogge** [comment]
`make test` does not run for me at all:
`henning.rogge@rogge-dev:~/develop/testbed/yangson (xml %=)$ LC_ALL=C make test
make: py.test: Command not found`

(the "%" is git complaining that I did not commit the .pybuild directory)

but pytest3 works nice:
> henning.rogge@rogge-dev:~/develop/testbed/yangson (xml %=)$ pytest-3 
> ==================================== test session starts ====================================
> platform linux -- Python 3.7.3, pytest-3.10.1, py-1.7.0, pluggy-0.9.0
> rootdir: /home/henning.rogge/develop/testbed/yangson, inifile:
> plugins: cov-2.6.0
> collected 9 items                                                                           
>
> tests/test_model.py .........                                                         [100%]
>
> ================================= 9 passed in 0.47 seconds ==================================

Any idea what is going on? I did run pytest before pushing...

**Comment by llhotka** [comment]
The `pytest` package is listed in `requirements.txt`. In `master`, `make test` runs properly, but in your `xml` branch, I am getting the exception
```
yangson.exceptions.MissingAugmentTarget: /t:choiA
```
raised from
```
    def _augment_stmt(self, stmt: Statement, sctx: SchemaContext) -> None:
        """Handle **augment** statement."""
        if not sctx.schema_data.if_features(stmt, sctx.text_mid):
            return
        path = sctx.schema_data.sni2route(stmt.argument, sctx)
        target = self.get_schema_descendant(path)
        if target is None:
>           raise MissingAugmentTarget(stmt.argument)
```

**Comment by HRogge** [comment]
Okay, I am confused... "make test" (with pytest3) is running fine for me.
Maybe a problem that depends on the version of python?

I tested with:
```
$ make test
=========== test session starts ===========
platform linux -- Python 3.7.3, pytest-3.10.1, py-1.7.0, pluggy-0.9.0
```
Distribution is a current Debian Stable.

**Comment by llhotka** [comment]
I have Python 3.8.2. I will try to check if it can cause the problem.

**Comment by HRogge** [comment]
I just did a fresh clone in a new directory... besides the necessary (on Debian?) rename of py.test to py.test-3 I had no trouble... ```make test``` reports 9 successful tests.

**Comment by llhotka** [comment]
Hmm, do you use a virtual environment? If not, can you try these steps?

https://github.com/CZ-NIC/yangson/wiki/devinstall

**Comment by HRogge** [comment]
I just did...
```
$ git clone git@github.com:CZ-NIC/yangson.git
$ python3 -m venv yangson
$ cd yangson
$ source bin/activate
$ make install-deps
...
Successfully installed Babel-2.3.3 Jinja2-2.10.1 MarkupSafe-0.23 PyXB-1.2.4 Pygments-2.1.3 Sphinx-1.8.4 alabaster-0.7.7 appdirs-1.4.0 args-0.1.0 astroid-1.4.5 bleach-3.1.5 certifi-2019.9.11 chardet-3.0.4 clint-0.5.1 colorama-0.3.7 docutils-0.14 idna-2.7 imagesize-0.7.0 lazy-object-proxy-1.2.2 packaging-16.8 pkginfo-1.5.0.1 py-1.4.31 pylint-1.5.5 pyparsing-2.1.10 pytest-2.9.1 pytz-2016.3 readme-renderer-24.0 requests-2.20.0 requests-toolbelt-0.9.1 six-1.10.0 snowballstemmer-1.2.1 sphinx-rtd-theme-0.1.9 sphinxcontrib-websupport-1.1.2 tqdm-4.38.0 twine-1.13.0 urllib3-1.24.3 webencodings-0.5.1 wrapt-1.10.8 yangson
$ make test
==================================== test session starts ====================================
platform linux -- Python 3.7.3, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir: /home/henning.rogge/tmp/yangson, inifile: 
collected 9 items 

tests/test_model.py .........

================================= 9 passed in 0.54 seconds ==================================
```

**Comment by llhotka** [comment]
Of course, this works for me, too. What I meant was to clone _your_ repo, setup venv, switch to the `xml` branch, and run `make test`.

I tried to clone your repo directly, and got the same exception.

**Comment by HRogge** [comment]
Okay, I can finally reproduce the exception... in fact I git NINE of them. I will try to look into this later.

**Comment by HRogge** [comment]
I think I have found the change that causes the trouble... but I am still not sure the change is wrong.

When I added the additional xml_namespace and modules_by_name/ns dictionaries in schemadata.py SchemaData() class, I had to rewrite a part of _from_yang_library().

The problematic section happens in the loop that loads the submodules... for some reason the ModuleData() for the submodule was instantiated with the parent modules "mid"...
Which I changed during the rewrite to "smid" (calculated from the submodules name and revision).

Most likely I mixed up the meaning of the main_module variable of ModuleData and "fixed" it to the right yang_id... and forgot about it during the rest of the XML mess.

I STILL have no clue why the problem does not happen without the venv.

**Comment by llhotka** [comment]
OK, the test now passes. I also still don't understand the need for the ` XMLParser` class. All elements in the structure produced by `ET.parse` seem to have namespaces recorded in their `tag`. What's the problem?

**Comment by HRogge** [comment]
The problem has two parts...

first,  ET.parse removes all xmlns-like attributes and includes the used one in the tag name. The other namespaces are not available.

second, Restconf (Netconf) XML encoding sometimes use namespaces in the value (text part!) of XML encoding. You will find an example in [RFC 8040 Section 4.5.](https://tools.ietf.org/html/rfc8040#section-4.5), where they use the jbox namespace that is NOT used by the nodes of the XML tree.

I see no way to get the jbox namespace except for using an improved parser.

**Comment by llhotka** [comment]
OK, I see. So I tried the following script with the tacasplus data model:
```
from yangson import DataModel
from yangson.enumerations import ContentType
from yangson.xmlparser import XMLParser

dm = DataModel.from_file(
    'yang-library.json',
    ['.', '../../../yang-modules/ietf',
     '/home/lhotka/lib/yang/standard/ietf/RFC'])
with open('example-data.xml') as infile:
    xp = XMLParser(infile.read())
inst = dm.from_xml(xp.root)
inst.validate(ctype=ContentType.all)
```
I hope it is the correct way of using `XMLParser`. I am getting the following exception:
```
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    xp = XMLParser(infile.read())
  File "/home/lhotka/Projects/yangson/yangson/xmlparser.py", line 45, in __init__
    self.parse()
  File "/home/lhotka/Projects/yangson/yangson/xmlparser.py", line 64, in parse
    del self._namespaces[ns_name]
KeyError: ''
```

**Comment by HRogge** [comment]
Can you try again? The last set of XML parser changes got pushed into the wrong feature branch.
I am working of a patch set that allows you to add "submodels" to a yangson datamodel, so you can handle all parts of the Restconf data store as a single model without rewriting YANG files.

**Comment by llhotka** [comment]
Yes, it works now. I tried to change the IP address `1.2.3.4` in `example-data.xml` to `1.2.3.4.5`, and got
```
yangson.exceptions.YangTypeError: [/ietf-system:system/dns-resolver/server/server=odvr/udp-and-tcp/address] None
```
If I do the same with the corresponding JSON instance, I get
```
yangson.exceptions.YangTypeError: [/ietf-system:system/dns-resolver/server/server=odvr/udp-and-tcp/address] expected union value
```

**Comment by HRogge** [comment]
I searched through the whole datatype.py and found a few missing cases of to/from_xml function.
I now get the same error for your xml example as you described in the JSON case.

**Comment by llhotka** [comment]
Good, it seems to work now. It would be useful to repeat all the tests in `test_model.py` on instance data read from XML. I tried to convert the JSON file using pyang but ran into a bug:
https://github.com/mbj4668/pyang/issues/626
Hopefully they can fix it soon because otherwise converting JSON to XML would be somewhat laborious.

I have a question regarding the XMLParser class:  why do you override the methods `feed` and `close` if you only call the same superclass method from them? And related: why do you use `super().read_events()` instead of simply `self.read_events()`?

**Comment by HRogge** [comment]
(I had an unpleasant run in with pyang myself before I switched to yangson...)
In theory you could load the data into the yangson instance and then re-export it with to_xml()... but that would not help to find bugs in my yangson XML code.

When I started digging into the XMLParser mess I wasn't sure what I had to overwrite and what I had to extend... so I started with overwriting everything to get an idea what is going on... I was still in a state of denial that Python wasn't be able to give me the XML namespaces in another way.

most likely I can drop feed/close() and call self.read_events(), as you said... 

shall I add a patch to the xml branch for it? (can you squash all commits of the xml branch before merging them?)

**Comment by llhotka** [comment]
I tried `to_xml` in the `yang_modules/test` directory with this script
```
(yangson) $ cat test.py 
import json
from yangson import DataModel
from yangson.enumerations import ContentType

dm = DataModel.from_file(
    'yang-library.json', ['.', '../ietf'])
with open('test-data.json') as infile:
    ri = json.load(infile)
inst = dm.from_raw(ri)
inst.to_xml()
```
and JSON instance
```
{
    "test:llistB": ["::1", "127.0.0.1"],
    "test:leafX": 53531,
    "test:contA": {
        "leafB": 9,
        "listA": [{
            "leafE": "C0FFEE",
            "leafF": true,
            "contD": {
                "leafG": "foo1-bar",
                "contE": {
                    "leafJ": [null],
                    "leafP": 10
                }
            }
        },
		  {
                      "leafE": "ABBA",
                      "leafW": 9,
                      "leafF": false
		  }],
        "testb:leafS":
        "/test:contA/listA[leafE='C0FFEE'][leafF='true']/contD/contE/leafP",
        "testb:leafR": "C0FFEE",
        "testb:leafT": "test:CC-BY",
        "testb:leafV": 99,
        "anydA": {
            "foo:bar": [1, 2, 3]
        },
        "testb:leafN": "hi!"
    },
    "test:contT": {
        "bits": "dos cuatro",
        "decimal64": 4.50,
        "enumeration": "Hearts"
    }
}
```
and got this exception:
```
(yangson) $ python test.py 
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    inst.to_xml()
  File "/home/lhotka/Projects/yangson/yangson/instance.py", line 434, in to_xml
    raise MissingModuleNamespace(self.schema_node.ns)
yangson.exceptions.MissingModuleNamespace: <exception str() failed>
```
Am I doing anything wrong?

**Comment by HRogge** [comment]
Not really, I think the problem is that you cannot easily express the "data" node (the one below all the user data models) in XML.

JSON is always surrounded by a "nameless dict", but XML starts with a single XML tag as the root.
The problem is that the RootNode() class does not have a namespace... But the XML root tag MUST have a namespace attached to it.

I managed to solve this for my restconfserver with adding "Submodule" support (attach module A to a point in module B), so I can put a "ietf-restconf" module below the modules in the /data directory. Maybe we could pretend that RootNode() is just part of ietf-restconf., I am not sure.

**Comment by llhotka** [comment]
In pyang I solved this by using an element from the NETCONF namespace, e.g.
```
<nc:data xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
```
Another option is to use the new instance file format from [draft-ietf-netmod-yang-instance-file-format](https://tools.ietf.org/html/draft-ietf-netmod-yang-instance-file-format)

**Comment by HRogge** [comment]
We just need to add the namespace both to the root schema_node and to the schema_data (where I get the mapping between JSON namespace names and XML namespaces)... or make it a special case stored in the model somewhere.

Maybe a "add root namespace" call in the SchemaData class?
```def add_root_namespace(self, module_name, xml_urn):```

Not sure about the draft, it doesn't look like a perfect fit for what we need at the moment, more like a new feature.

**Comment by llhotka** [comment]
My idea was to just hijack their document element
```
 <instance-data-set xmlns="urn:ietf:params:xml:ns:yang:ietf-yang-instance-data">
```
without necessarily using the additional metadata.

**Comment by HRogge** [comment]
If you look at [draft-ietf-netmod-yang-instance-file-format-12 section-3](https://tools.ietf.org/html/draft-ietf-netmod-yang-instance-file-format-12#section-3) you will see that this would be wrong, because the level below this node is NOT what the level below RestConf /data looks like.

```<data xmlns="urn:ietf:params:xml:ns:yang:ietf-restconf">```

might be more appropriate, but it depends on the usecase. That's why I suggested that we allow the user to define the tuple (tag name, xmlns and maybe yang module-name).

**Comment by llhotka** [comment]
OK, maybe
```
<content-data xmlns="urn:ietf:params:xml:ns:yang:ietf-yang-instance-data">
```
would be a better match.
Requiring the user to specify the root element is a bit clumsy.

**Comment by HRogge** [comment]
We could set one of the options the default and allow the user to overwrite it.

**Comment by llhotka** [comment]
Yes, this makes sense.

**Comment by HRogge** [comment]
I will add a suggestion and push it to the xml branch.

**Comment by HRogge** [comment]
The new commit works with the following test, as long as you remove the "anydata" content:

```
import json
from yangson import DataModel
from yangson.enumerations import ContentType
import xml.etree.ElementTree as ET

dm = DataModel.from_file(
    'yang-library.json', ['.', '../ietf'])
with open('test-data.json') as infile:
    ri = json.load(infile)
inst = dm.from_raw(ri)
root = inst.to_xml()

print(ET.tostring(root))
```

AnyData and AnyXML is quite broken in YANG because XML/JSON encoding depends on the schema of the anydata/anyxml stuff. Especially when you want to support XML and JSON.

I am still thinking about this problem.

Oh, the xml branch is also missing some parts of the Annotation support JSON already has, but I am planning on adding this. I just wanted to get some base code out to you first.

**Comment by HRogge** [comment]
Okay, here is an idea for the anyxml/anydata processing.

The library could allow to user to attach a class with a "from/to_xml" function for one (or multiple) data_paths of the model, which would then do the translation from JSON and XML to the internal representation and back.

We could provide the current code as a "translate JSON only" example for the class.

This way the user of the library can implement the kind of translation needed for the app.

**Comment by HRogge** [comment]
#53 came up during my work on a more clean json/xml import/output for RPC data.

**Comment by kwatsen** [comment]
Curious, what is the current status on this PR?

**Comment by kwatsen** [comment]
I wrote some test code and got some stuff working in both directions.  My test case does NOT have any `anydata` or metadata.  

The biggest technical issue is that `to_xml()` only exported the first of several top-level nodes.  I assume this is the same issue discussed above for what a dummy outer element (e.g., <content-data>) is needed.  This is unexpected as [this comment above](https://github.com/CZ-NIC/yangson/pull/51#issuecomment-631475124) suggests that it should work (i.e., test-data.json has multiple top-level entries)

The biggest non-technical issue is that there's no documentation.  It took me some time to figure out the parameters.  Also, "allow_nodata" not a good parameter name; even after looking the source code for how it's used, it still isn't intuitive...

I'm interested in using this API for a constrained use-case (effectively to support just two RESTCONF RPCs with no `anydata` or metadata).  _I'm wondering if it might be possible to **merge** this PR as a hidden/undocumented feature and/or with a flag (e.g., `enable_xml`) that must be set?_  

If so, then I'm willing to migrate my code to use this API and, in the process of doing so, give this API more testing and (if needed) help to resolve issues found...

**Comment by kwatsen** [comment]
No comments?

BTW, I posted a [GitHub issue against `yanglint`](https://github.com/CESNET/libyang/issues/1272) about the XML file format for when multiple top-level nodes exist, and Radek said that the XML-parts can just be concatenated together, like a multi-part PEM file.  It's technically illegal (as it was with PEM), but too convenient and options are poor.  Personally, I think Yangson, and the whole NETCONF universe should move to do the same.  Anything else seems like bending over backwards for a bad design decision in the XML format...actually, it wouldn't surprise me if this is already a thing, perhaps even supported by a standards-based extension of some sort (e.g., a different XML-declaration header line)

**Comment by HRogge** [comment]
Sorry, the main issue is "not enough time" on both sides... I have a fork/branch of yangson that can do XML input/output and the ability to hook in "sub-yang" files (for adding standardized YANG definitions into a larger yang file from the user), but it is (of course) not completely up to date anymore compared to yangson master.

I am also trying to get the ok from work to publish my attempt to write a Restconf server, but it is difficult... :(

**Comment by kwatsen** [comment]
Nothing to be sorry about, we're all busy!  ;)

Can you say some more about the "sub-yang files" issue?   Do you mean "sub-modules" or something more along the lines of imports that augment a base model?   In either case, doesn't Yangson do the heavy lifting of merging the schemas, and the only XML-impact is mapping namespaces correctly?

Stated another way, and in continuation of the idea of "can we merge/release the PR as a hidden and/or disabled feature", could the limitations be enumerated?  For instance, I understand that `anydata` and metadata are unsupported, what else?

Thanks,
Kent

**Comment by kwatsen** [comment]
Hi Henning,

I'm sure you noticed the Lada merged your PR - congrats.   

You might've also noticed that I submitted a PR to patch some code that broke non-XML applications (see PR #65).  

I'm now in the process of a "light" integration in my project.   By "light", I mean to say that the logic only needs to support a handful of relatively small data models, none of which have `anydata` or metadata.  That said, the logic very much needs to transcode all of these data models in every way imaginable.

The reason I'm writing is because I just found another issue that, thankfully, only affects the XML code.  I believe this issue is simply because the `isroot` parameter isn't used anywhere, which is odd since you clearly spent time to provision it.

Below fixes my immediate issue - what do you think?
```
    def from_xml(self, root: ET.Element) -> RootNode:
        """Create an instance node from a raw data tree.

        Args:
            robj: Dictionary representing a raw data tree.

        Returns:
            Root instance node.
        """
-        cooked = self.schema.from_xml(root)
+        cooked = self.schema.from_xml(root, isroot=True)
        return RootNode(cooked, self.schema, self.schema_data, cooked.timestamp)
```

I imagine that this issue MAY be related to the issue of how to support multiple top-level nodes, and the discussion around needing to wrap the nodes with the dummy-element, but see [my comment above](https://github.com/CZ-NIC/yangson/pull/51#issuecomment-726826840).  What do you think about this?

PPS: please write me directly `kent at watsen dot net` so we can discuss some things off GitHub.

Thanks,
Kent

**Comment by HRogge** [comment]
Thank you for merging my changes...

as I said in a mail to @kwatsen , "isroot" is a parameter to force a full namespace tag... I need this when combining multiple yang-models into a larger tree (which I do in my "submodels" branch).

I will send a pull request for "submodels" after we talked about #54

**Pull request merged**
